#!/bin/sh

ln -snf /usr/lib/enigma2/python/Plugins/Extensions/WebInterface/web-data/tpl/default/tplCurrent.htm /usr/lib/enigma2/python/Plugins/Extensions/WebAdmin/web-data/tpl/tplCurrent.htm
ln -snf /usr/lib/enigma2/python/Plugins/Extensions/WebInterface/web-data/tpl/default/tplVolume.htm /usr/lib/enigma2/python/Plugins/Extensions/WebAdmin/web-data/tpl/tplVolume.htm
ln -snf /usr/lib/enigma2/python/Plugins/Extensions/WebInterface/web-data/tpl/default/tplEpgList.htm /usr/lib/enigma2/python/Plugins/Extensions/WebAdmin/web-data/tpl/tplEpgList.htm

CONF=/usr/lib/enigma2/python/Plugins/Extensions/WebAdmin/web-data/terminal.conf

if [ ! -f "$CONF" ]
then
cat >> $CONF << EOF
# This file is part of "JTA - Telnet/SSH for the JAVA(tm) platform".
#
# (c) Matthias L. Jugel, Marcus Meißner 1996-2005. All Rights Reserved.
#
# Please visit http://javatelnet.org/ for updates and contact.
#
# --LICENSE NOTICE--
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
# --LICENSE NOTICE--
#

# This is an example file how to configure the applet. It may contain
# any property defined in de/mud/jta/default.conf or by a plugin.
#
#====================================
# intern or VPN
# Socket.host		=	192.168.1.153
# Socket.port		=	23
EOF
fi
