#!/bin/sh
echo "******************************************************"
echo "*                                                    *"
echo "* Subtitle Downloader installed                      *"
echo "* Homepage: http://code.google.com/p/subs-downloader/*"
echo "*                                                    *"
echo "* code by Silelis (c) 2011                           *"
echo "*                                                    *"
echo "* Restart Enigma-2 GUI to add plugin into plugin list*"
echo "******************************************************"
exit 0
